USE [QLDSV]
	DELETE FROM DIEM
	INSERT INTO DIEM
	SELECT * FROM  (SELECT MASV,MAMH, 1 AS LAN, ABS(CHECKSUM(NewId())) % 4 AS DIEM FROM (SELECT TOP 8000 MASV FROM SINHVIEN ORDER BY MASV) AS SV, MONHOC WHERE MAMH IN ('CSDL','CSDLPT')) AS TMP

	INSERT INTO DIEM
	SELECT * FROM  (SELECT MASV,MAMH, 1 AS LAN, ABS(CHECKSUM(NewId())) % 10 AS DIEM FROM (SELECT TOP 2000 MASV FROM SINHVIEN ORDER BY MASV DESC) AS SV, MONHOC WHERE MAMH NOT IN ('CSDL','CSDLPT')) AS TMP1